In [1]:
from gazpacho import Soup
import pandas as pd
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By

In [3]:
options = Options()
options.headless = True
service = Service('/usr/local/bin/geckodriver')
browser = Firefox(service=service, options=options)

In [4]:
url = "https://scrape.world/season"
browser.get(url)

#### Login

In [5]:
username = browser.find_element(By.NAME, "username")
username.clear()
username.send_keys("admin")

password = browser.find_element(By.ID, "password")
password.clear()
password.send_keys("admin")

browser.find_element(By.XPATH, "/html/body/div/div/form/div/input[3]").click()

In [6]:
browser.get(url)
html = str(browser.page_source)

In [7]:
tables = pd.read_html(html)

In [8]:
east = tables[0]
west = tables[1]

In [9]:
east.head()

,Rk,Team,W,L,OL,PTS,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division
1,1,Boston Kodiaks,48.5,18.8,14.7,111.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Tampa Bay Thunder,50.2,24.1,7.7,108.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Florida Jaguars,44.5,28.3,9.2,98.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = pd.concat([east, west], axis=0)
df["W"] = df["W"].apply(pd.to_numeric, errors="coerce")
df = df.dropna(subset=["W"])
df = df[["Team", "W"]]
df = df.rename(columns={"Team": "team", "W": "wins"})
df = df.sort_values("wins", ascending=False)

In [11]:
df

                        team  wins
11    Washington Investments  51.9
2          Tampa Bay Thunder  50.2
12        Pittsburgh Puffins  49.1
1             Boston Kodiaks  48.5
2         Colorado Landslide  47.3
1         St. Louis Doldrums  46.6
13       New York Indwellers  46.5
15         Carolina Cyclones  45.9
3         Dallas Celebrities  44.8
3            Florida Jaguars  44.5
10          Vancouver Whales  44.1
17   Philadelphia Travellers  43.1
14       Columbus Navy Coats  43.0
5       Toronto Pine Needles  42.5
11          Edmonton Workers  41.9
12    Vegas Shining Templars  41.6
18        New York Officials  40.5
6         Winnipeg Airplanes  40.4
4       Nashville Carnivores  40.2
13            Arizona Dingos  40.1
15            Calgary Flares  39.9
8           Minnesota Savage  39.0
7        Chicago Greyfalcons  38.9
6         Montreal Quebecers  38.8
16       San Jose Charlatans  36.0
7             Buffalo Knives  36.0
17          Anaheim Mallards  35.1
19         New Jersey Demons  31.9
18      Los Angeles Monarchs  31.0
8         Ottawa Legislators  29.9
9   Detroit Carmine Feathers  21.7

#### JavaScript

In [12]:
url = "https://scrape.world/results"
browser.get(url)

In [13]:
search = browser.find_element(By.XPATH, "/html/body/div/div/div[2]/div[2]/label/input")
search.clear()
search.send_keys("toronto")

In [14]:
drop_down = Select(
    browser.find_element(By.XPATH, "/html/body/div/div/div[2]/div[1]/label/select")
)
drop_down.select_by_visible_text("100")

In [15]:
html = browser.page_source

In [16]:
type(html)

str

In [17]:
soup = Soup(html)

In [18]:
df = pd.read_html(str(soup.find("table")))[0]

In [19]:
df

,day,away,goals_away,home,goals_home,extra_time_loss
0,1,Ottawa Legislators,3,Toronto Pine Needles,5,0
1,3,Toronto Pine Needles,4,Columbus Navy Coats,1,0
2,4,Montreal Quebecers,6,Toronto Pine Needles,5,1
3,6,St. Louis Doldrums,3,Toronto Pine Needles,2,0
4,9,Tampa Bay Thunder,7,Toronto Pine Needles,3,0
5,11,Toronto Pine Needles,5,Detroit Carmine Feathers,2,0
6,14,Minnesota Savage,2,Toronto Pine Needles,4,0
7,15,Toronto Pine Needles,3,Washington Investments,4,0
8,18,Boston Kodiaks,3,Toronto Pine Needles,4,1
9,20,Columbus Navy Coats,4,Toronto Pine Needles,3,1
10,21,Toronto Pine Needles,2,Boston Kodiaks,4,0
11,24,San Jose Charlatans,1,Toronto Pine Needles,4,0
12,25,Toronto Pine Needles,2,Montreal Quebecers,5,0
13,28,Washington Investments,4,Toronto Pine Needles,3,1
14,32,Toronto Pine Needles,4,Philadelphia Travellers,3,1
15,35,Los Angeles Monarchs,1,Toronto Pine Needles,3,0
16,37,Vegas Shining Templars,1,Toronto Pine Needles,2,1
17,39,Philadelphia Travellers,3,Toronto Pine Needles,2,1
18,40,Toronto Pine Needles,4,Chicago Greyfalcons,5,0
19,43,Toronto Pine Needles,4,New York Indwellers,5,0
20,45,Boston Kodiaks,4,Toronto Pine Needles,2,0
21,46,Toronto Pine Needles,1,Pittsburgh Puffins,6,0
22,49,Toronto Pine Needles,2,Vegas Shining Templars,4,0
23,51,Toronto Pine Needles,3,Arizona Dingos,1,0
24,53,Toronto Pine Needles,5,Colorado Landslide,3,0
25,57,Toronto Pine Needles,6,Detroit Carmine Feathers,0,0
26,59,Toronto Pine Needles,4,Buffalo Knives,6,0
27,60,Buffalo Knives,1,Toronto Pine Needles,2,1
28,63,Toronto Pine Needles,1,Philadelphia Travellers,6,0
29,64,Colorado Landslide,3,Toronto Pine Needles,1,0
30,67,Toronto Pine Needles,5,St. Louis Doldrums,2,0
31,70,Toronto Pine Needles,4,Vancouver Whales,1,0
32,72,Toronto Pine Needles,2,Calgary Flares,4,0
33,74,Toronto Pine Needles,4,Edmonton Workers,1,0
34,77,Buffalo Knives,3,Toronto Pine Needles,5,0
35,80,Toronto Pine Needles,6,New York Officials,3,0
36,81,Detroit Carmine Feathers,1,Toronto Pine Needles,4,0
37,83,Carolina Cyclones,6,Toronto Pine Needles,8,0
38,87,Toronto Pine Needles,5,New Jersey Demons,4,1
39,88,New York Officials,5,Toronto Pine Needles,4,1
40,91,Toronto Pine Needles,4,Minnesota Savage,1,0
41,93,Toronto Pine Needles,6,Winnipeg Airplanes,3,0
42,95,New York Indwellers,0,Toronto Pine Needles,3,0
43,97,Edmonton Workers,6,Toronto Pine Needles,4,0
44,99,Winnipeg Airplanes,4,Toronto Pine Needles,3,1
45,103,Toronto Pine Needles,4,Florida Jaguars,8,0
46,105,New Jersey Demons,4,Toronto Pine Needles,7,0
47,107,Calgary Flares,2,Toronto Pine Needles,1,1
48,109,Chicago Greyfalcons,6,Toronto Pine Needles,2,0
49,118,Toronto Pine Needles,5,Nashville Carnivores,2,0
50,120,Toronto Pine Needles,5,Dallas Celebrities,3,0
51,123,Ottawa Legislators,1,Toronto Pine Needles,2,1
52,125,Florida Jaguars,5,Toronto Pine Needles,3,0
53,127,Toronto Pine Needles,3,New York Officials,5,0
54,129,Anaheim Mallards,4,Toronto Pine Needles,5,1
55,130,Toronto Pine Needles,1,Montreal Quebecers,2,1
56,133,Arizona Dingos,2,Toronto Pine Needles,3,1
57,135,Dallas Celebrities,3,Toronto Pine Needles,2,0